site_name: Desafio 4
site_description: Documentacao do Sistema de Gestao de Presenca Academica da equipe Moranguetes.
repo_url: https://github.com/menali17/Desafio_4_Trainee_EngNet
repo_name: menali17/Desafio_4_Trainee_EngNet

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

exclude_docs: |
  casos_de_uso.md
  planejamento/cronograma.md
  planejamento/atas.md

nav:
  - Início: index.md
  - Setup Tecnico: setup_tecnico.md

  - Visão do Produto e Projeto:
      - Visão Geral: visao/index.md
      - Cenário Atual: visao/cenario_atual.md
      - Matriz CSD: visao/matriz_csd.md
      - Objetivos: visao/objetivos.md
      - Perfil e Personas: visao/perfil_personas.md
      - Solução Proposta: visao/solucao_proposta.md

  - Requisitos e Backlog:
      - Visão Geral: backlog/index.md
      - Histórias de Usuário: backlog/historias_usuario.md
      - Requisitos: backlog/requisitos.md
      - Priorização: backlog/priorizacao.md
      - Backlog do Produto: backlog/backlog_produto.md

  - Planejamento:
      - Visão Geral: planejamento/index.md
      - Metodologia: planejamento/metodologia.md

  - Arquitetura e Desenvolvimento:
      - Banco de Dados: arquitetura/banco_de_dados.md

  - Boas Práticas:
      - Visão Geral: boas_praticas/index.md
      - Padrão de Branches: boas_praticas/padrao_branch.md
      - Padrão de Commits: boas_praticas/padrao_commit.md
